# Generated by Django 3.0 on 2021-05-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('availabilities', '0002_auto_20200418_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time'], 'verbose_name_plural': 'availabilities'},
        ),
    ]
