# Generated by Django 3.0 on 2021-04-22 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicians.Clinician'),
        ),
    ]
