# Generated by Django 3.0 on 2021-05-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '__first__'),
        ('appointments', '0002_appointment_clinician'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient'),
            preserve_default=False,
        ),
    ]
