# Generated by Django 3.0 on 2021-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('availabilities', '0002_auto_20200418_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('national_provider_identifier', models.CharField(max_length=10, unique=True)),
                ('availabilities', models.ManyToManyField(through='appointments.Appointment', to='availabilities.Availability')),
            ],
        ),
    ]
