# Generated by Django 3.0 on 2021-04-21 22:17

from django.db import migrations


def seed_clinicians(apps, schema_editor):
    Clinician = apps.get_model("clinicians", "Clinician")
    clinician = Clinician.objects.create(
        first_name="Cynthia", last_name="Clinician", national_provider_identifier="1234567890",
    )
    clinician.save()
    clinician = Clinician.objects.create(
        first_name="Carl", last_name="Clinician", national_provider_identifier="0987654321"
    )
    clinician.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clinicians", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_clinicians),
    ]
