export const GET_APPOINMENTS = 'GET_APPOINMENTS';
export const GET_AVAILABILITIES = 'GET_AVAILABILITIES';
export const GET_CLINICIANS = 'GET_CLINICIANS';
export const GET_PATIENTS = 'GET_PATIENTS';

export const GET_APPOINMENT = 'GET_APPOINMENT';
export const GET_AVAILABILITIE = 'GET_AVAILABILITIE';
export const GET_CLINICIAN = 'GET_CLINICIAN';
export const GET_PATIENT = 'GET_PATIENT';

export const ADD_APPOINMENT = 'ADD_APPOINMENT';
export const ADD_AVAILABILITIE = 'ADD_AVAILABILITIE';
export const ADD_CLINICIAN = 'ADD_CLINICIAN';
export const ADD_PATIENT = 'ADD_PATIENT';

export const DELETE_APPOINMENT = 'DELETE_APPOINMENT';
export const DELETE_AVAILABILITIE = 'DELETE_AVAILABILITIE';
export const DELETE_CLINICIAN = 'DELETE_CLINICIAN';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const EDIT_APPOINMENT = 'EDIT_APPOINMENT';
export const EDIT_AVAILABILITIE = 'EDIT_AVAILABILITIE';
export const EDIT_CLINICIAN = 'EDIT_CLINICIAN';
export const EDIT_PATIENT = 'EDIT_PATIENT';